# Generated by Django 5.1.4 on 2026-04-28 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squarebox', '0002_property_user_alter_property_bedrooms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['user', 'datamode'], name='property_user_id_fce093_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_by', 'datamode'], name='property_created_10dc7a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-updated_on'], name='property_updated_ae4fa7_idx'),
        ),
    ]
