# Generated by Django 5.1.4 on 2026-04-28 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squarebox', '0003_alter_property_created_by_alter_property_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='squarebox.property'),
        ),
    ]
